baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "rinoldsimon.github.io" # the base hostname & protocol for your site.
title: "rinoldsimon"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/rinoldsimon"  #Add your github url here.
wordpress: "http://learnrubyblog.wordpress.com/" #Add your wordpress url here.
twitter: "https://twitter.com/crisrinold"  #Add your twitter url here.
linkedin: "in.linkedin.com/pub/rinold-simon/68/108/244/"
facebook: "https://www.facebook.com/crisrinold"

gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
